name: Web Service Continuous Integration
on:
  push:
    branches: [main]
jobs:
 
  packer_init_validate_build:
    runs-on: ubuntu-latest
    name: Build AWS Custom AMI with Node Application artifacts
    steps:
      - name: Step 6 - Build Artifacts and create Custom AMI from Packer Build
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: aws-ami.pkr.hcl
        env:
          PACKER_LOG: 1
  





