name: Web Service Continuous Integration
on:
  pull_request:
    branches: [main]
jobs:      
  packer_init_validate:
    runs-on: ubuntu-latest
    name: Validate Packer for the AMI Build
    steps: 
      - name: Step 1 - Checkout code from branch
        uses: actions/checkout@v2

      - name: Step 2 - zip all the webService files
        run: |
          zip -r webservice.zip ./
          pwd ./webservice

      - name: Step 3 - Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: aws-ami.pkr.hcl

      - name: Step 4 - Validate Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: aws-ami.pkr.hcl